### ISSUE TITLE
Container going in an unhealthy state every few minutes if nothing is being watched.

### ISSUE THREAD

**Issue by JourneyOver** [Valentin-Metz/TwitchDropsMiner#61]
Unsure of what has exactly changed but I am going to assume it's to do with this commit https://github.com/Valentin-Metz/TwitchDropsMiner/commit/f996ca5cedb4b6ae5a311ae999bdb2767fffa6fa but going over my autoheal log, and watching the actual container that if there is nothing being farmed the container runs into the unhealthy bug issue that we talked about [here](https://github.com/Valentin-Metz/TwitchDropsMiner/pull/49#issuecomment-1985061378).

Just a snippet of my autoheal log:

```

11-06-2024 14:04:53 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:07:04 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:09:15 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:11:25 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:13:36 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:15:47 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:17:58 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:20:09 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:22:20 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:24:31 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:26:41 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:28:52 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:31:03 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:33:14 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:35:25 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:37:36 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:39:47 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:41:58 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:44:09 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:46:20 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:48:30 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:50:41 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:52:52 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:55:03 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
11-06-2024 14:57:14 Container /twitchdropsminer (a2c8729e7dfa) found to be unhealthy - Restarting container now with 10s timeout
```

this is the only thing happening between these unhealthy sessions:

```

2024-06-11 09:55:14: Started new container
2024-06-11 09:55:14: Starting: Twitch Drops Miner
2024-06-11 09:55:15: Logging level: CALL
2024-06-11 09:55:15: INFO: Checking login
2024-06-11 09:55:15: INFO: Restoring session from cookie
2024-06-11 09:55:15: INFO: Login successful, user ID: {ID}
2024-06-11 09:55:15: INFO: Websocket[0] connecting...
2024-06-11 09:55:16: INFO: Websocket[0] connected.
2024-06-11 09:55:25: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-11 09:55:25: CALL: Maintenance task waiting until: 09:58:59 (Cleanup)
2024-06-11 09:57:25: Started new container
2024-06-11 09:57:25: Starting: Twitch Drops Miner
2024-06-11 09:57:25: Logging level: CALL
2024-06-11 09:57:26: INFO: Checking login
2024-06-11 09:57:26: INFO: Restoring session from cookie
2024-06-11 09:57:26: INFO: Login successful, user ID: {ID}
2024-06-11 09:57:26: INFO: Websocket[0] connecting...
2024-06-11 09:57:27: INFO: Websocket[0] connected.
2024-06-11 09:57:35: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-11 09:57:35: CALL: Maintenance task waiting until: 09:58:59 (Cleanup)

```

if something is being farmed then the container doesn't seem to go to an unhealthy state until after everything is farmed.

**Comment by Valentin-Metz** [comment]
Should be fixed with b6db7f3d603ea3c1c23cb9d78f3a00189e168845.

**Comment by JourneyOver** [comment]
Honestly I ended up reverting the https://github.com/Valentin-Metz/TwitchDropsMiner/commit/f996ca5cedb4b6ae5a311ae999bdb2767fffa6fa commit as well as reverting to not using the whole timeout thing you re-added after I made this issue and up till watchtower updated the twitchdropsbot to your latest release everything was working perfectly.. 

but anyways yea... it's still not fixed with the whole https://github.com/Valentin-Metz/TwitchDropsMiner/commit/b6db7f3d603ea3c1c23cb9d78f3a00189e168845 commit... Looks like it's going into an unhealthy state every 2-3 minutes and then autoheal restarts the container again in just an infinite loop, if I turn off autoheal container then twitchdropsminer just sits in an unhealthy state forever.

**Comment by Valentin-Metz** [comment]
Have the logs changed?

**Comment by JourneyOver** [comment]
Hmm so something must of bugged last night when it did the pull for the b6db7f3 commit, as I repulled everything today and it's working a bit better than before, it's still going into an unhealthy state however but it looks to be every 5-7 minutes give or take going by autoheal.

Autoheal log:
```log
AUTOHEAL_CONTAINER_LABEL=all
AUTOHEAL_START_PERIOD=0
AUTOHEAL_INTERVAL=60
AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
AUTOHEAL_ONLY_MONITOR_RUNNING=true
16-06-2024 20:12:49 Container /twitchdropsminer (8ab73c20ea66) found to be unhealthy - Restarting container now with 10s timeout
16-06-2024 20:19:01 Container /twitchdropsminer (8ab73c20ea66) found to be unhealthy - Restarting container now with 10s timeout
16-06-2024 20:25:12 Container /twitchdropsminer (8ab73c20ea66) found to be unhealthy - Restarting container now with 10s timeout
16-06-2024 20:31:23 Container /twitchdropsminer (8ab73c20ea66) found to be unhealthy - Restarting container now with 10s timeout
16-06-2024 20:40:34 Container /twitchdropsminer (8ab73c20ea66) found to be unhealthy - Restarting container now with 10s timeout
16-06-2024 20:46:45 Container /twitchdropsminer (8ab73c20ea66) found to be unhealthy - Restarting container now with 10s timeout
16-06-2024 20:52:57 Container /twitchdropsminer (8ab73c20ea66) found to be unhealthy - Restarting container now with 10s timeout
16-06-2024 20:59:08 Container /twitchdropsminer (8ab73c20ea66) found to be unhealthy - Restarting container now with 10s timeout
```

TDM Log:
```log
2024-06-16 15:06:49: Started new container
2024-06-16 15:06:49: Starting: Twitch Drops Miner
2024-06-16 15:06:51: Logging level: CALL
2024-06-16 15:06:51: INFO: Checking login
2024-06-16 15:06:51: INFO: Restoring session from cookie
2024-06-16 15:06:51: INFO: Login successful, user ID: {ID}
2024-06-16 15:06:51: INFO: Websocket[0] connecting...
2024-06-16 15:06:52: INFO: Websocket[0] connected.
2024-06-16 15:07:17: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:07:17: CALL: Maintenance task waiting until: 15:34:59 (Cleanup)
2024-06-16 15:13:00: Started new container
2024-06-16 15:13:00: Starting: Twitch Drops Miner
2024-06-16 15:13:01: Logging level: CALL
2024-06-16 15:13:01: INFO: Checking login
2024-06-16 15:13:01: INFO: Restoring session from cookie
2024-06-16 15:13:02: INFO: Login successful, user ID: {ID}
2024-06-16 15:13:02: INFO: Websocket[0] connecting...
2024-06-16 15:13:02: INFO: Websocket[0] connected.
2024-06-16 15:13:11: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:13:11: CALL: Maintenance task waiting until: 15:34:59 (Cleanup)
2024-06-16 15:19:11: Started new container
2024-06-16 15:19:12: Starting: Twitch Drops Miner
2024-06-16 15:19:12: Logging level: CALL
2024-06-16 15:19:13: INFO: Checking login
2024-06-16 15:19:13: INFO: Restoring session from cookie
2024-06-16 15:19:13: INFO: Login successful, user ID: {ID}
2024-06-16 15:19:13: INFO: Websocket[0] connecting...
2024-06-16 15:19:13: INFO: Websocket[0] connected.
2024-06-16 15:19:23: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:19:23: CALL: Maintenance task waiting until: 15:34:59 (Cleanup)
2024-06-16 15:25:23: Started new container
2024-06-16 15:25:23: Starting: Twitch Drops Miner
2024-06-16 15:25:23: Logging level: CALL
2024-06-16 15:25:24: INFO: Checking login
2024-06-16 15:25:24: INFO: Restoring session from cookie
2024-06-16 15:25:24: INFO: Login successful, user ID: {ID}
2024-06-16 15:25:24: INFO: Websocket[0] connecting...
2024-06-16 15:25:25: INFO: Websocket[0] connected.
2024-06-16 15:25:34: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:25:34: CALL: Maintenance task waiting until: 15:34:59 (Cleanup)
2024-06-16 15:31:34: Started new container
2024-06-16 15:31:34: Starting: Twitch Drops Miner
2024-06-16 15:31:35: Logging level: CALL
2024-06-16 15:31:35: INFO: Checking login
2024-06-16 15:31:35: INFO: Restoring session from cookie
2024-06-16 15:31:35: INFO: Login successful, user ID: {ID}
2024-06-16 15:31:35: INFO: Websocket[0] connecting...
2024-06-16 15:31:36: INFO: Websocket[0] connected.
2024-06-16 15:31:45: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:31:45: CALL: Maintenance task waiting until: 15:34:59 (Cleanup)
2024-06-16 15:35:00: CALL: Maintenance task requests channels cleanup
2024-06-16 15:35:00: CALL: Maintenance task waiting until: 16:05:00 (Points)
2024-06-16 15:35:00: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:40:45: Started new container
2024-06-16 15:40:45: Starting: Twitch Drops Miner
2024-06-16 15:40:46: Logging level: CALL
2024-06-16 15:40:46: INFO: Checking login
2024-06-16 15:40:46: INFO: Restoring session from cookie
2024-06-16 15:40:47: INFO: Login successful, user ID: {ID}
2024-06-16 15:40:47: INFO: Websocket[0] connecting...
2024-06-16 15:40:47: INFO: Websocket[0] connected.
2024-06-16 15:40:56: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:40:56: CALL: Maintenance task waiting until: 16:10:56 (Points)
2024-06-16 15:46:56: Started new container
2024-06-16 15:46:56: Starting: Twitch Drops Miner
2024-06-16 15:46:57: Logging level: CALL
2024-06-16 15:46:57: INFO: Checking login
2024-06-16 15:46:57: INFO: Restoring session from cookie
2024-06-16 15:46:58: INFO: Login successful, user ID: {ID}
2024-06-16 15:46:58: INFO: Websocket[0] connecting...
2024-06-16 15:46:58: INFO: Websocket[0] connected.
2024-06-16 15:47:06: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:47:06: CALL: Maintenance task waiting until: 16:17:06 (Points)
2024-06-16 15:53:07: Started new container
2024-06-16 15:53:07: Starting: Twitch Drops Miner
2024-06-16 15:53:08: Logging level: CALL
2024-06-16 15:53:08: INFO: Checking login
2024-06-16 15:53:08: INFO: Restoring session from cookie
2024-06-16 15:53:09: INFO: Login successful, user ID: {ID}
2024-06-16 15:53:09: INFO: Websocket[0] connecting...
2024-06-16 15:53:09: INFO: Websocket[0] connected.
2024-06-16 15:53:18: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:53:18: CALL: Maintenance task waiting until: 16:23:18 (Points)
2024-06-16 15:59:18: Started new container
2024-06-16 15:59:19: Starting: Twitch Drops Miner
2024-06-16 15:59:19: Logging level: CALL
2024-06-16 15:59:19: INFO: Checking login
2024-06-16 15:59:19: INFO: Restoring session from cookie
2024-06-16 15:59:20: INFO: Login successful, user ID: {ID}
2024-06-16 15:59:20: INFO: Websocket[0] connecting...
2024-06-16 15:59:20: INFO: Websocket[0] connected.
2024-06-16 15:59:29: No active campaigns to mine drops for. Waiting for an active campaign...
2024-06-16 15:59:29: CALL: Maintenance task waiting until: 16:29:29 (Points)
```

**Comment by JourneyOver** [comment]
@Valentin-Metz any updates on this? also it seems that a lot of recent updates done on the main repo, hasn't been getting pulled to this repo?

also I suggest grabbing the [lastAwardedAt](https://github.com/Windows200000/TwitchDropsMiner-updated/commit/a04dab7588c3bee542ef1c14ac2f28bd97322065) changes and implementing them as well now as there is a major bug on twitches side of things makes the bot sit there and farm something that has been collected for ever unless you either implement this change, or remove the game from the priority list in the settings.

**Comment by Valentin-Metz** [comment]
The maintenance task wait is an architectural issue sadly.
We can count it as progress and wait (potentially missing a state inconsistency), or we can keep the current state and just restart (since restarting the container is free if we have nothing to farm anyway).
I'll probably leave it as-is for a bit longer, until I find a more elegant solution.

I've integrated the changes from windows, but the changes from DevilXD will take some more manual work to merge in, so expect that within the next few days. After that I'll re-enable the automatic upstream merger from DevilXDs repository, so there should be no further delays beyond.

**Comment by JourneyOver** [comment]
Hmm sounds good, I ended up having to re-add the timeout thing as of recent back to my container sadly though as it did seem to finally have some type of breaking issue with it hitting a point where it just gets stuck on "can't connect to twitch" until I restart the container but one thing I've noticed recently is that I get the following error every so often `/bin/sh: 1: arithmetic expression: expecting ')': " (60 - 08) * 60 - 33 "` with the default command, not really sure on what the exact cause is on why this is happening as it happens a couple times when it does happen and then eventually randomly fixes itself.

**Comment by Valentin-Metz** [comment]
> I've noticed recently is that I get the following error every so often `/bin/sh: 1: arithmetic expression: expecting ')': " (60 - 08) * 60 - 33 "` 

Fixed with e257dba43e60651424ab017da0658739f678af84.

**Comment by JourneyOver** [comment]
> the changes from DevilXD will take some more manual work to merge in, so expect that within the next few days. After that I'll re-enable the automatic upstream merger from DevilXDs repository, so there should be no further delays beyond.

Any updates about this?

**Comment by JourneyOver** [comment]
@Valentin-Metz I'm getting a bunch of random errors now with this sadly like:
```

2024-08-04 14:01:23: Fatal error encountered:

2024-08-04 14:01:23: Traceback (most recent call last):
  File "/TwitchDropsMiner/main.py", line 160, in main
    await client.run()
  File "/TwitchDropsMiner/twitch.py", line 773, in run
    await self._run()
  File "/TwitchDropsMiner/twitch.py", line 818, in _run
    await self.fetch_inventory()
  File "/TwitchDropsMiner/twitch.py", line 1679, in fetch_inventory
    chunk_campaigns_data = await chunk_coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 631, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/TwitchDropsMiner/twitch.py", line 1622, in fetch_campaigns
    (campaign_data := response_json["data"]["user"]["dropCampaign"])["id"]: campaign_data
                      ~~~~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'

2024-08-04 14:01:23: Exiting...
2024-08-04 14:01:23: INFO: Websocket[0] stopped.
2024-08-04 14:01:24: 
Application Terminated.
Close the window to exit the application
```

and:
```

2024-08-04 13:58:24: Fatal error encountered:

2024-08-04 13:58:24: Traceback (most recent call last):
  File "/TwitchDropsMiner/main.py", line 160, in main
    await client.run()
  File "/TwitchDropsMiner/twitch.py", line 773, in run
    await self._run()
  File "/TwitchDropsMiner/twitch.py", line 818, in _run
    await self.fetch_inventory()
  File "/TwitchDropsMiner/twitch.py", line 1662, in fetch_inventory
    available_list: list[JsonType] = response["data"]["currentUser"]["dropCampaigns"] or []
                                     ~~~~~~~~^^^^^^^^
KeyError: 'data'

2024-08-04 13:58:24: Exiting...
```

**Comment by Valentin-Metz** [comment]
> KeyError: 'data'

Should be fixed with latest upstream merge.

**Comment by JourneyOver** [comment]
@Valentin-Metz  

yea those was fixed, but def running into a new one today and unsure what exactly is going on, start up of the container is fine and all but then after about ~20-30 seconds or so (from the looks of it) it throws a huge error and then sits there failing to connect to twitch until I restart the container which then just repeats the process again. 

[twitchdropsminer_logs.txt](https://github.com/user-attachments/files/16566099/twitchdropsminer_logs.txt)

I've tried restarting the container multiple times over, and every time it'll just repeat the same process again and again.

**Comment by JourneyOver** [comment]
Yea something def broke with this between two days ago and today unsure of what exactly though and I sadly can't really test and see if it's something to do with the container or not fully as your build dev version action hasn't been run in 3 months now so your release section is super out of date.

But running https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.8.1 (sadly can't run it as a container) and haven't ran into the same issue (I do run into a diff one to do with: ```14:59:01: ERROR: Exception in task
14:59:01: Traceback (most recent call last):
14:59:01:   File "utils.py", line 139, in wrapper
14:59:01:   File "twitch.py", line 1398, in process_drops
14:59:01: asyncio.exceptions.InvalidStateError: invalid state``` however) but everything seems to continue to run just fine so it def feels like it's something in this repo that is causing the issue I talked about int he logs file in the comment above.

**Comment by Valentin-Metz** [comment]
> It sits there failing to connect to twitch until I restart the container which then just repeats the process again.

Twitch has recently de-authed some old sessions. Delete your cookies and your cache folder, and re-login.

**Comment by Valentin-Metz** [comment]
I wasn't aware anyone is intending to use this fork from a release.
Easiest way to run this should be to either run the published docker image, or clone the repository and just execute `main.py` with python.
New dev-release versions will from now on automatically be compiled on push.

**Comment by JourneyOver** [comment]
> Twitch has recently de-authed some old sessions. Delete your cookies and your cache folder, and re-login.

I had tried that as well and it was having the same problem of logging in and then after X amount of seconds throwing the errors I had shown in the log.

> I wasn't aware anyone is intending to use this fork from a release.
> Easiest way to run this should be to either run the published docker image, or clone the repository and just execute main.py with python.
> New dev-release versions will from now on automatically be compiled on push.

I wasn't intending on using this fork from the release section, it was mainly to just run a test from the release section downloads and see if it was something specific to just the docker container or not.

**Comment by Valentin-Metz** [comment]
> I had tried that as well and it was having the same problem of logging in and then after X amount of seconds throwing the errors I had shown in the log.

I can't reproduce this right now; here everything appears to be working fine.
Try clearing the entire state, by deleting every persistent file except settings and recreating the container.

**Comment by JourneyOver** [comment]
Sorry it took me so long to get back to this, been dealing with a lot of random crap IRL anyways I'm not really sure what was going on those days but whatever it was seems to have resolved itself from what I can tell as the errors haven't come back up any yet.

**Comment by Valentin-Metz** [comment]
Stuff like this is usually an upstream issue and gets fixed once they release a patch.

**Comment by JourneyOver** [comment]
I'm going to go ahead and close this issue up as I've pretty much forked off and moved my upstream over to DevilXDs codebase with just a few slight additions from this repository and ofc my own changes as well.
